apiVersion: v2
name: my-app
description: A Helm chart for deploying my application
type: application
version: 1.0.0
appVersion: "1.0.0"
maintainers:
  - name: Krishna Kishore
    email: your.email@example.com
keywords:
  - flutter
  - mobile
  - app
  - cross-platform
home: https://yourprojecthomepage.example.com
sources:
  - https://github.com/yourusername/your-repo

